### ISSUE TITLE
bootstrap.sh fails in fedora

### ISSUE THREAD

**Issue by dpensi** [edenhill/kafkacat#223]
after running bootstrap.sh i receive the following output
```
.
.
.
cp: cannot stat '/home/dpensier/prg/kafkacat/tmp-bootstrap/usr/share/pkgconfig/*.pc': No such file or directory
Directory libyajl already exists, not downloading https://github.com/edenhill/yajl/archive/edenhill.tar.gz
Building libyajl with commands:
([ -d build ] || ./configure --prefix /home/dpensier/prg/kafkacat/tmp-bootstrap/usr) && make distro && make install
make: *** No rule to make target 'distro'.  Stop.
Build of libyajl FAILED!
```

**Comment by dgcapone** [comment]
Hi!.   did you solve the issue? I'm running the same problem but in RH7. Thanks for your help.

**Comment by dpensi** [comment]
unfortunately no, I'm sorry

**Comment by edenhill** [comment]
Fixed on master

**Comment by prashantochatterjee** [comment]
I am still getting this issue on Centos (CentOS Linux release 7.8.2003 (Core)) with the latest code.

`Build of librdkafka SUCCEEDED!
cp: cannot stat ‘/home/macaw/kafkacat/tmp-bootstrap/usr/share/pkgconfig/*.pc’: No such file or directory
Directory libyajl already exists, not downloading https://github.com/edenhill/yajl/archive/edenhill.tar.gz
Building libyajl with commands:
([ -d build ] || ./configure --prefix /home/macaw/kafkacat/tmp-bootstrap/usr) && make install
make: *** No rule to make target `install'.  Stop.
Build of libyajl FAILED!
`

**Comment by VadimJCA** [comment]
Note, that if you go directly into `tmp_bootsrap/libyajl` and do
`./configure --prefix /data/kafkacat/tmp-bootstrap/usr) && make install`
it will fail on missing librdkafka. So, after you `sudo yum install librdkafka-devel` - it will compile and you can go back up to bootstap.sh... and fail on cannot find -lcurl even after you yum the curl to your box.
